name: refetch
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: ^3.12.0

dependencies:
  appwrite: ^24.2.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^21.0.0
  flutter_riverpod: ^3.3.1
  go_router: ^17.2.3
  http: ^1.6.0
  permission_handler: ^12.0.2
  push: ^3.3.3
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  mocktail: ^1.0.5

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android: true
  adaptive_icon_background: "#5A00FF"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  adaptive_icon_monochrome: "assets/icon/icon_foreground.png"
  ios: true
  remove_alpha_ios: true
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 256
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#5A00FF"
    theme_color: "#5A00FF"
